editor:
  render-on-save: true

project:
  type: website
  preview:
    port: 3000
    browser: false
    watch-inputs: true

website:
  title: "Austen Lamacraft"
  navbar:
    right:
      - posts.qmd
      - talks.qmd
      - teaching.qmd
      - cv.qmd
      - icon: google
        href: https://scholar.google.com/citations?user=ERR4TF0AAAAJ&hl=en
      - icon: github
        href: https://github.com/AustenLamacraft
      - icon: twitter
        href: https://twitter.com/AustenLamacraft
  favicon: favicon-32x32-roboto-slab.png
  twitter-card: true

format:
  html:
    theme: cosmo
    css: styles.css



