editor:
  render-on-save: true

project:
  type: website
  preview:
    port: 3000
    browser: false
    watch-inputs: true

website:
  title: "Austen Lamacraft"
  navbar:
    right:
      - talks.qmd
      - about.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/AustenLamacraft
      - icon: twitter
        href: https://twitter.com/AustenLamacraft

format:
  html:
    theme: cosmo
    css: styles.css



